//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topping.Common.Sources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GroupDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GroupDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topping.Common.Sources.GroupDescription", typeof(GroupDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витаминное смузи
        ///в любую пору года -
        ///это просто вместе с «Щедрик»! Берите за основу
        ///молоко, воду, мороженое или фрукты- овощи, добавляйте лед, порцию
        ///натурального сиропа и взбивайте в блендере..
        /// </summary>
        public static string BerryGroup {
            get {
                return ResourceManager.GetString("BerryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сиропы -TМ «Щедрик»
        ///универсальный модификатор для приготовления легендарных коктейлей
        ///«Пина Колада», «Голубая Лагуна», «Мохито», «Секс на
        ///пляже», «Текила Санрайз»,
        ///«Космополитен», «Дайкири», «Голубые Гавайи» ... А еще основа для Ваших авторских
        ///экспериментов! Фантазируйте и миксуйте вместе с «Щедрик»!.
        /// </summary>
        public static string CocktailGroup {
            get {
                return ResourceManager.GetString("CocktailGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ванильный раф, карамельное латте, шоколадное мокко, капучино с кленовым сиропом?
        ///А может эспрессо с
        ///ноткой ликеров «Амаретто» и «Ирландский крем»? Фраппе или глясе
        ///со вкусом пирожного «Тирамису», или оттенком орехового сиропа ... Легко! С сиропами
        ///ТМ «Щедрик»!.
        /// </summary>
        public static string CoffeeGroup {
            get {
                return ResourceManager.GetString("CoffeeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кроме воспроизводимого вкуса фруктов сиропы «Щедрик» добавляют напиткам еще и
        ///ожидаемые цвета и оттенки. Зеленое яблоко и банан, манго и дыня - самые смелые
        ///сочетания для вкусных освежающих лимонадов..
        /// </summary>
        public static string FruitGroup {
            get {
                return ResourceManager.GetString("FruitGroup", resourceCulture);
            }
        }
    }
}
